modLoader="javafml"
loaderVersion="[43,)"
license="Custom license"

[[mods]]
modId="theabyss"
version="2.9.7"
displayName="TheAbyss"
credits="Mod by Y3Z0N"
displayURL="https://www.curseforge.com/members/y4z0n/followers"
logoFile="logo.png"
authors="Y3Z0N"
description='''
The Abyss adds a brand new dimension to explore full of unique adventures and dangers! It's a dimension of darkness the only light comes from magical blocks and the various flora, fungi, and fauna of the dimension.
'''

[[dependencies.theabyss]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.theabyss]]
    modId="patchouli"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.theabyss]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

